# Generated by Django 4.0.3 on 2022-05-23 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DeviceProperty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_properties', to='web.device')),
            ],
            options={
                'db_table': 'properties',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('happened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='web.deviceproperty')),
            ],
            options={
                'db_table': 'measurements',
                'default_permissions': (),
            },
        ),
    ]
